# Generated by Django 4.2 on 2023-05-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_visualizationforipdetail_visitors_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='visualization',
            unique_together={('year', 'month')},
        ),
    ]
