# Generated by Django 4.2 on 2023-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0003_alter_visitors_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='page_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
