# Generated by Django 4.2 on 2023-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0004_project_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='email_it',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='message_it',
            field=models.TextField(blank=True, null=True, verbose_name='Messaggio'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='name_it',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome e Cognome'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='subject_it',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Oggetto'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject'),
        ),
    ]
