# Generated by Django 4.2 on 2023-05-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0005_contactform_email_it_contactform_message_it_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='email_it',
        ),
    ]
