# Generated by Django 4.2 on 2023-05-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0006_remove_contactform_email_it'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactItForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name_it', models.CharField(max_length=100, verbose_name='Nome e Cognome')),
                ('subject_it', models.CharField(max_length=200, verbose_name='Oggetto')),
                ('email_it', models.EmailField(max_length=254, verbose_name='Email')),
                ('message_it', models.TextField(verbose_name='Messaggio')),
            ],
            options={
                'verbose_name': 'Contact Profile',
                'verbose_name_plural': 'Contact Profiles',
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='message_it',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='name_it',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='subject_it',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
    ]
