# Generated by Django 4.2 on 2023-05-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0007_contactitform_remove_contactform_message_it_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactitform',
            old_name='email_it',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactitform',
            old_name='message_it',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactitform',
            old_name='name_it',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactitform',
            old_name='subject_it',
            new_name='subject',
        ),
    ]
